# Generated by Django 6.0.1 on 2026-07-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_student_profile_pic_student_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='syllabus',
            field=models.ImageField(blank=True, null=True, upload_to='syllabus/'),
        ),
    ]
